"use client";

import { Check, ClipboardCopy, FileCheck2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";

import type { ImportPreview } from "@/server/coach-import";

export function AdminProgrammeRequestWorkflow({ requestId, coachBrief }: { requestId: string; coachBrief: string }) {
  const router = useRouter(); const [copied, setCopied] = useState(false); const [json, setJson] = useState(""); const [preview, setPreview] = useState<ImportPreview | null>(null); const [approved, setApproved] = useState(false); const [error, setError] = useState(""); const [done, setDone] = useState(false);
  async function request(path: string, body: unknown) { const response = await fetch(`/api/admin/programme-requests/${requestId}/${path}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); return data; }
  async function copy() { await navigator.clipboard.writeText(coachBrief); setCopied(true); window.setTimeout(()=>setCopied(false), 2000); }
  async function validate() { setError(""); setPreview(null); try { const data = await request("preview", { json }); setPreview(data.preview); setApproved(false); } catch (caught) { setError(caught instanceof Error ? caught.message : "Validation failed"); } }
  async function apply() { setError(""); try { await request("apply", { json, confirmation: "CREATE_REQUEST_PROGRAMME" }); setDone(true); setPreview(null); router.refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Apply failed"); } }
  async function cancel() { if (!window.confirm("Cancel this pending programme request?")) return; try { await request("cancel", {}); router.replace("/admin/requests"); router.refresh(); } catch (caught) { setError(caught instanceof Error ? caught.message : "Cancel failed"); } }
  return <div className="space-y-7"><section className="rounded-3xl border bg-card p-5 shadow-sm sm:p-7"><h2 className="text-xl font-semibold">Coach-friendly export</h2><textarea readOnly value={coachBrief} className="mt-4 min-h-96 w-full rounded-2xl border bg-background p-4 font-mono text-xs leading-5"/><button onClick={()=>void copy()} className="mt-3 inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 font-semibold text-primary-foreground"><ClipboardCopy className="size-4"/>{copied ? "Copied" : "Copy coach brief"}</button></section><section className="rounded-3xl border bg-card p-5 shadow-sm sm:p-7"><h2 className="text-xl font-semibold">Create programme for request owner</h2><p className="mt-2 text-sm text-muted-foreground">Paste schemaVersion 2 JSON. Validation writes nothing.</p><textarea value={json} onChange={(event)=>setJson(event.target.value)} className="mt-4 min-h-72 w-full rounded-2xl border bg-background p-4 font-mono text-xs"/><button disabled={!json.trim() || done} onClick={()=>void validate()} className="mt-3 min-h-11 rounded-xl bg-foreground px-4 font-semibold text-white disabled:opacity-50">Validate programme</button>{error && <p role="alert" className="mt-3 rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}{done && <p className="mt-4 inline-flex items-center gap-2 rounded-xl bg-accent p-3 font-semibold text-accent-foreground"><Check className="size-4"/>Programme created, activated, and request completed.</p>}{preview && <div className="mt-5 rounded-2xl border bg-muted/50 p-4"><h3 className="font-semibold">Create {preview.programName} [{preview.program}] · version 1</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{preview.days.map((day)=><div key={day.slug} className="rounded-xl border bg-background p-3"><p className="font-medium">{day.name}</p><p className="text-xs text-muted-foreground">{day.exerciseCount} exercises · rotation {day.rotationOrder}</p></div>)}</div><p className="mt-4 text-sm">{preview.added.length} exercises will be added.</p><label className="mt-4 flex gap-3 rounded-xl border bg-card p-3 text-sm"><input type="checkbox" checked={approved} onChange={(event)=>setApproved(event.target.checked)}/><span>I reviewed this programme and want to create and activate it for the request owner.</span></label><button disabled={!approved} onClick={()=>void apply()} className="mt-3 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl bg-primary font-semibold text-primary-foreground disabled:opacity-50"><FileCheck2 className="size-5"/>Create and activate programme</button></div>}<button disabled={done} onClick={()=>void cancel()} className="mt-8 text-sm font-semibold text-destructive disabled:opacity-50">Cancel request</button></section></div>;
}
