"use client";

import { AlertTriangle, Check, Database, RefreshCw, Trash2 } from "lucide-react";
import { useCallback, useEffect, useState } from "react";

import { clearPrivateOfflineData, getActiveOfflineWorkout, getOfflineOutbox, getOfflineTimer } from "@/lib/offline-db";
import { syncOfflineMutations } from "@/lib/offline-sync";

type Details = { activeWorkout: string | null; queued: number; failed: number; timer: boolean; firstFailure: { type: string; sequence: number; attempts: number; error: string } | null };

export function OfflineStatusSettings() {
  const [details, setDetails] = useState<Details>(); const [busy, setBusy] = useState(false); const [confirming, setConfirming] = useState(false); const [message, setMessage] = useState("");
  const inspect = useCallback(async () => { const [workout, outbox, timer] = await Promise.all([getActiveOfflineWorkout(), getOfflineOutbox(), getOfflineTimer()]); const failed = outbox.find((item) => item.lastError); setDetails({ activeWorkout: workout?.workoutDayName ?? null, queued: outbox.length, failed: outbox.filter((item) => item.lastError).length, timer: Boolean(timer), firstFailure: failed ? { type: failed.type, sequence: failed.sequence, attempts: failed.attempts, error: failed.lastError! } : null }); }, []);
  useEffect(() => { const startup = window.setTimeout(() => { void inspect().catch(() => setMessage("Offline storage is unavailable in this browser.")); }, 0); return () => window.clearTimeout(startup); }, [inspect]);
  async function retry() { setBusy(true); setMessage(""); const status = await syncOfflineMutations(); await inspect(); setMessage(status === "synced" ? "All local changes are synchronized." : status === "needs-attention" ? "The first failed change still needs attention. Your queue was preserved." : "Changes remain safely stored on this device."); setBusy(false); }
  async function clear() { setBusy(true); setMessage(""); try { await clearPrivateOfflineData(); setDetails({ activeWorkout: null, queued: 0, failed: 0, timer: false, firstFailure: null }); setConfirming(false); setMessage("Private offline data and caches were cleared from this device."); } catch { setMessage("Offline data could not be cleared. Close other VicGym tabs and try again."); } finally { setBusy(false); } }
  return <section className="mt-6 rounded-3xl border bg-card p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-accent text-primary"><Database className="size-5"/></span><div><h2 className="text-lg font-semibold">Offline storage</h2><p className="text-sm text-muted-foreground">Private data held by this browser profile</p></div></div><dl className="mt-5 grid grid-cols-2 gap-3 text-sm"><Status label="Active workout" value={details?.activeWorkout ?? "None"}/><Status label="Queued changes" value={details ? String(details.queued) : "…"}/><Status label="Failed changes" value={details ? String(details.failed) : "…"}/><Status label="Rest timer" value={details?.timer ? "Saved" : "None"}/></dl>{details?.firstFailure && <div className="mt-4 rounded-2xl border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950"><div className="flex gap-2"><AlertTriangle className="mt-0.5 size-4 shrink-0"/><div><p className="font-semibold">First blocked change: {details.firstFailure.type} #{details.firstFailure.sequence}</p><p className="mt-1 break-words text-amber-900">{details.firstFailure.error}</p><p className="mt-1 text-xs text-amber-800">Retry attempts: {details.firstFailure.attempts}. Later changes remain safely queued in order.</p></div></div></div>}<button type="button" disabled={busy || !details?.queued} onClick={() => void retry()} className="mt-5 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border bg-card px-4 text-sm font-semibold disabled:opacity-50"><RefreshCw className={`size-4 ${busy ? "animate-spin" : ""}`}/>Retry synchronization</button>{!confirming ? <button type="button" disabled={busy} onClick={() => setConfirming(true)} className="mt-3 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl text-sm font-semibold text-destructive"><Trash2 className="size-4"/>Reset private offline data</button> : <div className="mt-3 rounded-2xl border border-amber-300 bg-amber-50 p-4"><div className="flex gap-2 text-sm text-amber-950"><AlertTriangle className="mt-0.5 size-4 shrink-0"/><p>This permanently removes the local workout, timer, unsynchronized queue, and private caches on this device. Synchronized server history is unchanged.</p></div><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={() => setConfirming(false)} className="min-h-10 rounded-xl border bg-white text-sm font-semibold">Cancel</button><button type="button" disabled={busy} onClick={() => void clear()} className="min-h-10 rounded-xl bg-destructive px-3 text-sm font-semibold text-white">Clear local data</button></div></div>}{message && <p role="status" className="mt-4 flex items-start gap-2 text-sm text-muted-foreground"><Check className="mt-0.5 size-4 shrink-0 text-primary"/>{message}</p>}</section>;
}

function Status({ label, value }: Readonly<{ label: string; value: string }>) { return <div className="rounded-2xl bg-background p-3"><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 truncate font-semibold">{value}</dd></div>; }
