"use client";

import { Clock3, Dumbbell, ListChecks } from "lucide-react";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";

import { ActiveExercise } from "@/components/active-exercise";
import { AppShell } from "@/components/app-shell";
import { CardioTimer } from "@/components/cardio-timer";
import { getOfflineWorkout, updateOfflineWorkout } from "@/lib/offline-db";
import type { OfflineWorkout } from "@/lib/offline-types";

export function OfflineWorkoutView({ sessionId, exerciseSessionId }: Readonly<{ sessionId: string; exerciseSessionId: string }>) {
  const router = useRouter();
  const [workout, setWorkout] = useState<OfflineWorkout | null | undefined>(undefined);
  useEffect(() => { void getOfflineWorkout(sessionId).then((local) => { setWorkout(local); if (local) void updateOfflineWorkout(sessionId, (current) => ({ ...current, currentExerciseId: exerciseSessionId, updatedAt: new Date().toISOString() })); }).catch(() => setWorkout(null)); }, [exerciseSessionId, sessionId]);
  if (workout === undefined) return <AppShell><main className="mx-auto w-full max-w-3xl flex-1 px-4 py-10 text-sm text-muted-foreground">Loading locally saved workout…</main></AppShell>;
  const exercise = workout?.exercises.find((item) => item.id === exerciseSessionId);
  if (!workout || !exercise) return <AppShell><main className="mx-auto w-full max-w-3xl flex-1 px-4 py-10"><h1 className="text-2xl font-semibold">Local workout unavailable</h1><p className="mt-3 text-muted-foreground">Reconnect to reload this workout from VicGym.</p><button type="button" onClick={() => router.push("/")} className="mt-6 inline-flex rounded-xl bg-primary px-4 py-3 font-semibold text-white">Return home</button></main></AppShell>;
  const index = workout.exercises.findIndex((item) => item.id === exercise.id); const previous = workout.exercises[index - 1]; const next = workout.exercises[index + 1];
  for (const set of exercise.sets) { set.loadTrackingType ??= exercise.loadTrackingType ?? null; set.loadEntryMode ??= exercise.loadEntryMode ?? null; }
  const imageStem = exercise.imagePath?.replace(/-1280\.webp$/, "");
  return <AppShell><main className="mx-auto w-full max-w-5xl flex-1 px-4 py-5 sm:px-8 sm:py-8"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-semibold text-primary">{workout.workoutDayName}</p><p className="mt-1 text-sm font-medium">Exercise {index + 1} of {workout.exercises.length}</p></div><a href={`/offline/finish/${sessionId}`} className="rounded-xl border bg-card px-3 py-2 text-sm font-semibold">Finish workout</a></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${((index + 1) / workout.exercises.length) * 100}%` }}/></div><CardioTimer sessionId={sessionId} initial={{ planned: workout.cardioPlanned ?? false, startedAt: workout.cardioStartedAt ?? null, stoppedAt: workout.cardioStoppedAt ?? null, durationSeconds: workout.cardioDurationSeconds ?? 0 }}/><article className="mt-5 overflow-hidden rounded-3xl border bg-card shadow-sm">{imageStem ? <picture><source type="image/avif" srcSet={`${imageStem}-640.avif 640w, ${imageStem}-1280.avif 1280w`}/><img src={`${imageStem}-1280.webp`} alt={`${exercise.equipmentName ?? exercise.name} used for ${exercise.name}`} width="1280" height="960" className="aspect-[4/3] max-h-[25rem] w-full object-cover"/></picture> : <div className="flex aspect-[4/3] max-h-[25rem] flex-col items-center justify-center gap-3 bg-accent px-6 text-center text-primary"><div className="grid size-14 place-items-center rounded-2xl border border-primary/15 bg-background"><Dumbbell className="size-7"/></div><div><p className="font-semibold">Exercise image not yet available</p><p className="mt-1 text-sm text-muted-foreground">A movement-specific image has not been added yet.</p></div></div>}<div className="p-5 sm:p-7"><p className="text-sm font-semibold text-primary">{exercise.equipmentName ?? "Bodyweight / no equipment"}</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">{exercise.name}</h1><p className="mt-2 text-xs font-semibold text-muted-foreground">Offline mode · changes are saved locally</p><div className="mt-4 grid grid-cols-3 gap-2"><div className="rounded-xl bg-background p-3"><ListChecks className="size-4 text-primary"/><p className="mt-2 text-xs text-muted-foreground">Plan</p><p className="font-semibold">{exercise.plannedSets} × {exercise.targetReps}</p></div><div className="rounded-xl bg-background p-3"><Clock3 className="size-4 text-primary"/><p className="mt-2 text-xs text-muted-foreground">Rest</p><p className="font-semibold">{exercise.restSeconds}s</p></div><div className="rounded-xl bg-background p-3"><Dumbbell className="size-4 text-primary"/><p className="mt-2 text-xs text-muted-foreground">Timer</p><p className="font-semibold">{exercise.autoRest ? "Auto" : "Manual"}</p></div></div><ActiveExercise sessionId={sessionId} exerciseSessionId={exercise.id} initialSets={exercise.sets} previousId={previous?.id ?? null} nextId={next?.id ?? null}/></div></article></main></AppShell>;
}
