type Point = { label: string; value: number };

export function ProgressChart({ points, label, unit = "" }: Readonly<{ points: Point[]; label: string; unit?: string }>) {
  if (!points.length) return <div className="rounded-2xl border border-dashed bg-muted/40 p-5 text-sm text-muted-foreground">No recorded values for this period.</div>;
  if (points.length === 1) return <div className="rounded-2xl border border-dashed bg-muted/40 p-5 text-sm text-muted-foreground">One recorded session: {points[0].value}{unit}. A trend appears after another completed session.</div>;
  const width = 320; const height = 156; const pad = 24; const values = points.map((point) => point.value); const min = Math.min(...values); const max = Math.max(...values); const range = max - min || 1;
  const coordinates = points.map((point, index) => ({ ...point, x: pad + (index * (width - pad * 2)) / (points.length - 1), y: height - pad - ((point.value - min) / range) * (height - pad * 2) }));
  return <figure className="overflow-hidden rounded-2xl border bg-background p-3" aria-label={label}><svg viewBox={`0 0 ${width} ${height}`} className="h-auto w-full" role="img" aria-label={`${label}. Values range from ${min}${unit} to ${max}${unit}.`}><line x1={pad} x2={width - pad} y1={height - pad} y2={height - pad} className="stroke-border" /><path d={coordinates.map((point, index) => `${index ? "L" : "M"}${point.x} ${point.y}`).join(" ")} fill="none" className="stroke-primary" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" />{coordinates.map((point) => <circle key={point.label} cx={point.x} cy={point.y} r="4" className="fill-primary stroke-card" strokeWidth="2"><title>{`${point.label}: ${point.value}${unit}`}</title></circle>)}<text x={pad} y={height - 5} className="fill-muted-foreground text-[10px]">{points[0].label}</text><text x={width - pad} y={height - 5} textAnchor="end" className="fill-muted-foreground text-[10px]">{points.at(-1)!.label}</text><text x={width - pad} y={14} textAnchor="end" className="fill-muted-foreground text-[10px]">{max}{unit}</text></svg><figcaption className="mt-2 text-xs text-muted-foreground">{label}</figcaption></figure>;
}
