"use client";

import { Check, ClipboardCopy, FileCheck2, RefreshCw, Send, Sparkles } from "lucide-react";
import { useState } from "react";

import type { ImportPreview } from "@/server/coach-import";
import type { WeeklyReview } from "@/server/weekly-review";

function PreviewGroup({ title, items }: Readonly<{ title: string; items: ImportPreview["changes"] }>) {
  if (!items.length) return null;
  return <section className="mt-4"><h3 className="text-sm font-semibold text-primary">{title}</h3><div className="mt-2 space-y-2">{items.map((item, index) => <article key={`${item.day}-${item.exercise}-${index}`} className="rounded-xl border bg-background p-3"><p className="font-medium">{item.exercise}</p><p className="text-xs text-muted-foreground">{item.day}</p><ul className="mt-2 space-y-1 text-sm">{item.details.map((detail) => <li key={detail}>{detail}</li>)}</ul></article>)}</div></section>;
}

export function ReviewWorkflow({ initialReview }: Readonly<{ initialReview: WeeklyReview }>) {
  const [review, setReview] = useState(initialReview); const [week, setWeek] = useState(initialReview.weekStart);
  const [loadingReport, setLoadingReport] = useState(false); const [copied, setCopied] = useState(false);
  const [json, setJson] = useState(""); const [preview, setPreview] = useState<ImportPreview | null>(null); const [validationError, setValidationError] = useState(""); const [applying, setApplying] = useState(false); const [approved, setApproved] = useState(false); const [applied, setApplied] = useState<number | null>(null);
  async function generate() { setLoadingReport(true); try { const response = await fetch(`/api/review/report?week=${encodeURIComponent(week)}`, { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setReview(data.review); } finally { setLoadingReport(false); } }
  async function copy() { try { await navigator.clipboard.writeText(review.report); setCopied(true); window.setTimeout(() => setCopied(false), 2000); } catch { setCopied(false); } }
  async function validate() { setValidationError(""); setPreview(null); setApplied(null); try { const response = await fetch("/api/review/import/preview", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ json }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setPreview(data.preview); setApproved(false); } catch (error) { setValidationError(error instanceof Error ? error.message : "Coach changes could not be validated."); } }
  async function apply() { if (!approved || !preview) return; setApplying(true); setValidationError(""); try { const response = await fetch("/api/review/import/apply", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ json, confirmation: "APPLY_COACH_CHANGES" }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setApplied(data.versionNumber); setPreview(null); setApproved(false); } catch (error) { setValidationError(error instanceof Error ? error.message : "Coach changes could not be applied."); } finally { setApplying(false); } }
  return <div className="mt-7 space-y-8">
    <section className="rounded-3xl border bg-card p-5 shadow-sm sm:p-7" aria-labelledby="weekly-report-title"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold text-primary">Weekly Report</p><h2 id="weekly-report-title" className="mt-1 text-2xl font-semibold tracking-tight">Copy for ChatGPT</h2></div><Sparkles className="size-6 text-primary"/></div><label className="mt-5 block text-sm font-medium">Week beginning (Monday)<input type="date" value={week} onChange={(event) => setWeek(event.target.value)} className="mt-2 block min-h-12 w-full rounded-xl border bg-background px-3"/></label><button type="button" disabled={loadingReport} onClick={() => void generate()} className="mt-3 inline-flex min-h-11 items-center gap-2 rounded-xl border bg-background px-4 text-sm font-semibold"><RefreshCw className="size-4"/>{loadingReport ? "Generating…" : "Generate / refresh report"}</button>{review.isEmpty ? <div className="mt-5 rounded-2xl bg-muted p-4 text-sm text-muted-foreground">No completed workouts were recorded for this Europe/London Monday–Sunday week. {review.programSlug ? "The export includes the active programme identifiers for a compatible coach response." : "Weekly patches require an active programme; initial schemaVersion 2 programme JSON can still be validated below."}</div> : <p className="mt-5 text-sm text-muted-foreground">{review.completedSessions} completed workout{review.completedSessions === 1 ? "" : "s"} · {review.workingSets} completed working sets</p>}<textarea readOnly value={review.report} aria-label="Weekly report preview" className="mt-5 min-h-96 w-full rounded-2xl border bg-background p-4 font-mono text-xs leading-5"/><button type="button" onClick={() => void copy()} className="mt-3 inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-white"><ClipboardCopy className="size-4"/>{copied ? "Copied" : "Copy for ChatGPT"}</button></section>
    <section className="rounded-3xl border bg-card p-5 shadow-sm sm:p-7" aria-labelledby="coach-import-title"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold text-primary">Import Coach Changes</p><h2 id="coach-import-title" className="mt-1 text-2xl font-semibold tracking-tight">Preview before applying</h2></div><FileCheck2 className="size-6 text-primary"/></div><p className="mt-3 text-sm leading-6 text-muted-foreground">Paste the structured JSON returned by ChatGPT. VicGym checks it against the current verified catalogue and programme version before showing any change.</p><textarea value={json} onChange={(event) => setJson(event.target.value)} placeholder={'{\n  "schemaVersion": 1,\n  "changes": []\n}'} aria-label="Coach JSON changes" className="mt-5 min-h-64 w-full rounded-2xl border bg-background p-4 font-mono text-xs leading-5"/><button type="button" onClick={() => void validate()} disabled={!json.trim()} className="mt-3 inline-flex min-h-11 items-center gap-2 rounded-xl bg-foreground px-4 text-sm font-semibold text-white disabled:opacity-50"><Send className="size-4"/>Validate changes</button>{validationError && <p role="alert" className="mt-3 rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{validationError}</p>}{applied && <p className="mt-4 inline-flex items-center gap-2 rounded-xl bg-accent px-3 py-2 text-sm font-semibold text-accent-foreground"><Check className="size-4"/>Programme version {applied} is now active.</p>}
      {preview && <div className="mt-6 rounded-2xl border bg-muted/50 p-4"><p className="text-sm font-semibold text-primary">{preview.kind === "create" ? "Preview new programme" : "Preview changes"}</p><h3 className="mt-1 text-lg font-semibold">{preview.kind === "create" ? `Create ${preview.programName} [${preview.program}] · version 1` : `Version ${preview.baseVersion} → ${preview.nextVersion}`}</h3>{preview.kind === "create" && <div className="mt-4 grid gap-2 sm:grid-cols-2">{preview.days.map((day) => <div key={day.slug} className="rounded-xl border bg-background p-3"><p className="font-medium">{day.name} <span className="text-xs text-muted-foreground">[{day.slug}]</span></p><p className="mt-1 text-xs text-muted-foreground">Rotation {day.rotationOrder} · {day.exerciseCount} exercises</p></div>)}</div>}<PreviewGroup title={preview.kind === "create" ? "Exercises to add" : "Changed"} items={preview.kind === "create" ? preview.added : preview.changed}/>{preview.kind === "patch" && <><PreviewGroup title="Added" items={preview.added}/><PreviewGroup title="Removed" items={preview.removed}/><PreviewGroup title="Reordered" items={preview.reordered}/></>}<label className="mt-5 flex items-start gap-3 rounded-xl border bg-card p-3 text-sm"><input type="checkbox" checked={approved} onChange={(event) => setApproved(event.target.checked)} className="mt-0.5 size-5 accent-[var(--primary)]"/><span>{preview.kind === "create" ? "I have reviewed this programme and want to create version 1 and activate it." : `I have reviewed this preview and want to create and activate programme version ${preview.nextVersion}.`}</span></label><button type="button" disabled={!approved || applying} onClick={() => void apply()} className="mt-3 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl bg-primary px-5 font-semibold text-white disabled:opacity-50"><FileCheck2 className="size-5"/>{applying ? "Applying…" : preview.kind === "create" ? "Create and activate programme" : "Apply changes and activate"}</button></div>}
    </section>
  </div>;
}
