import { ArrowRight, ClipboardList } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";

import { getPrisma } from "@/lib/prisma";
import { listProgrammeRequests, normalizeRequestFilter, questionnaireLabel, requestFilters } from "@/server/admin-programme-requests";
import { requireCurrentUser } from "@/server/auth";

export const dynamic = "force-dynamic";
const filterNames = { PENDING: "Pending", COMPLETED: "Completed", CANCELLED: "Cancelled", ALL: "All" } as const;
const statusClasses = { PENDING: "bg-amber-100 text-amber-900", COMPLETED: "bg-emerald-100 text-emerald-900", CANCELLED: "bg-slate-200 text-slate-700" } as const;

export default async function AdminRequestsPage({ searchParams }: { searchParams: Promise<{ status?: string | string[] }> }) {
  const user = await requireCurrentUser(); if (user.role !== "ADMIN") redirect("/"); const filter = normalizeRequestFilter((await searchParams).status); const requests = await listProgrammeRequests(getPrisma(), filter);
  return <main className="mx-auto w-full max-w-4xl flex-1 px-4 py-7 sm:px-8 sm:py-10"><p className="text-sm font-semibold text-primary">Administrator</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">Personalised programme requests</h1><p className="mt-2 text-sm text-muted-foreground">Review coach briefs and create initial programmes without accessing workout history.</p><nav aria-label="Request status filters" className="mt-6 flex gap-2 overflow-x-auto pb-1">{requestFilters.map((value)=><Link key={value} href={`/admin/requests?status=${value}`} className={`shrink-0 rounded-full px-4 py-2 text-sm font-semibold ${filter === value ? "bg-primary text-primary-foreground" : "border bg-card"}`}>{filterNames[value]}</Link>)}</nav><div className="mt-5 space-y-3">{requests.map((request)=>{ const profile=request.user.onboardingProfile; return <Link key={request.id} href={`/admin/requests/${request.id}`} className="block rounded-2xl border bg-card p-4 shadow-sm transition hover:border-primary"><div className="flex items-start gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-2xl bg-accent text-primary"><ClipboardList className="size-5"/></span><span className="min-w-0 flex-1"><span className="flex flex-wrap items-center gap-2"><strong className="truncate">{request.user.email}</strong><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${statusClasses[request.status]}`}>{filterNames[request.status]}</span></span><span className="mt-1 block text-xs text-muted-foreground">Submitted {request.createdAt.toLocaleString("en-GB")}</span></span><ArrowRight className="mt-2 size-4 shrink-0 text-muted-foreground"/></div><dl className="mt-4 grid grid-cols-3 gap-2 text-xs"><Meta label="Goal" value={questionnaireLabel(profile?.goal)}/><Meta label="Frequency" value={profile?.trainingDaysPerWeek ? `${profile.trainingDaysPerWeek} days` : "—"}/><Meta label="Session" value={profile?.sessionLengthMinutes ? `${profile.sessionLengthMinutes} min` : "—"}/></dl></Link>;})}{!requests.length && <div className="rounded-3xl border bg-card p-7 text-sm text-muted-foreground">No {filter === "ALL" ? "" : filterNames[filter].toLowerCase()} requests found.</div>}</div></main>;
}
function Meta({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-background p-2.5"><dt className="text-muted-foreground">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>; }
