import { notFound, redirect } from "next/navigation";

import { AdminProgrammeRequestWorkflow } from "@/components/admin-programme-request-workflow";
import { AppShell } from "@/components/app-shell";
import { getPrisma } from "@/lib/prisma";
import { buildCoachBrief, questionnaireLabel } from "@/server/admin-programme-requests";
import { requireCurrentUser } from "@/server/auth";

export const dynamic = "force-dynamic";
const statusClasses = { PENDING: "bg-amber-100 text-amber-900", COMPLETED: "bg-emerald-100 text-emerald-900", CANCELLED: "bg-slate-200 text-slate-700" } as const;

export default async function AdminRequestPage({ params }: { params: Promise<{ requestId: string }> }) {
  const user = await requireCurrentUser(); if (user.role !== "ADMIN") redirect("/"); const { requestId } = await params; const data = await buildCoachBrief(getPrisma(), requestId).catch(()=>null); if (!data) notFound(); const profile = data.request.user.onboardingProfile; const activeProgram = data.request.user.settings?.activeProgram;
  return <AppShell><main className="mx-auto w-full max-w-5xl flex-1 px-4 py-7 sm:px-8 sm:py-10"><p className="text-sm font-semibold text-primary">Administrator review</p><div className="mt-1 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-semibold tracking-tight">{data.request.user.email}</h1><span className={`rounded-full px-3 py-1 text-xs font-semibold ${statusClasses[data.request.status]}`}>{questionnaireLabel(data.request.status)}</span></div><p className="mt-2 text-sm text-muted-foreground">Submitted {data.request.createdAt.toLocaleString("en-GB")}{data.request.completedAt ? ` · Completed ${data.request.completedAt.toLocaleString("en-GB")}` : ""}{data.request.cancelledAt ? ` · Cancelled ${data.request.cancelledAt.toLocaleString("en-GB")}` : ""}</p>{data.request.status === "COMPLETED" && <section className="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-emerald-800">Active programme</p><p className="mt-1 font-semibold text-emerald-950">{activeProgram?.name ?? "Programme metadata unavailable"}{activeProgram?.activeVersion ? ` · Version ${activeProgram.activeVersion.versionNumber}` : ""}</p><p className="mt-1 text-xs text-emerald-800">[{activeProgram?.slug ?? "unknown"}]</p></section>}<section className="my-7 rounded-3xl border bg-card p-5 shadow-sm sm:p-7"><h2 className="text-xl font-semibold">Coach Brief</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><Brief label="Goal" value={questionnaireLabel(profile?.goal)}/><Brief label="Training frequency" value={profile?.trainingDaysPerWeek ? `${profile.trainingDaysPerWeek} days per week` : null}/><Brief label="Session length" value={profile?.sessionLengthMinutes ? `${profile.sessionLengthMinutes} minutes` : null}/><Brief label="Experience" value={questionnaireLabel(profile?.experience)}/><Brief label="Cardio preference" value={questionnaireLabel(profile?.cardioPreference)}/><Brief label="Training preferences" value={profile?.trainingPreferences}/><Brief label="Limitations" value={profile?.hasLimitations ? profile.limitationsText : "None reported"}/><Brief label="Personal priorities" value={profile?.personalPriorities}/><Brief label="Additional notes" value={profile?.additionalNotes}/></div></section><AdminProgrammeRequestWorkflow requestId={requestId} coachBrief={data.markdown} aiPrompt={data.aiPrompt} requestStatus={data.request.status} ownerEmail={data.request.user.email}/></main></AppShell>;
}
function Brief({ label, value }: { label: string; value: string | number | null | undefined }) { return <section className="rounded-2xl bg-background p-4"><h3 className="text-xs font-semibold uppercase tracking-wide text-primary">{label}</h3><p className="mt-1 whitespace-pre-wrap text-sm leading-6">{value || "Not provided"}</p></section>; }
