import { notFound, redirect } from "next/navigation";

import { AdminProgrammeRequestWorkflow } from "@/components/admin-programme-request-workflow";
import { AppShell } from "@/components/app-shell";
import { getPrisma } from "@/lib/prisma";
import { buildCoachBrief } from "@/server/admin-programme-requests";
import { requireCurrentUser } from "@/server/auth";

export const dynamic = "force-dynamic";
export default async function AdminRequestPage({ params }: { params: Promise<{ requestId: string }> }) { const user = await requireCurrentUser(); if (user.role !== "ADMIN") redirect("/"); const { requestId } = await params; const data = await buildCoachBrief(getPrisma(), requestId).catch(()=>null); if (!data) notFound(); const profile = data.request.user.onboardingProfile; return <AppShell><main className="mx-auto w-full max-w-5xl flex-1 px-4 py-7 sm:px-8 sm:py-10"><p className="text-sm font-semibold text-primary">Administrator review</p><h1 className="mt-1 text-3xl font-semibold tracking-tight">{data.request.user.email}</h1><p className="mt-2 text-sm text-muted-foreground">Submitted {data.request.createdAt.toLocaleString("en-GB")} · {data.request.status}</p><section className="my-7 grid gap-3 rounded-3xl border bg-card p-5 shadow-sm sm:grid-cols-2 sm:p-7"><Brief label="Goal" value={profile?.goal}/><Brief label="Frequency" value={profile?.trainingDaysPerWeek ? `${profile.trainingDaysPerWeek} days per week` : null}/><Brief label="Session" value={profile?.sessionLengthMinutes ? `${profile.sessionLengthMinutes} minutes` : null}/><Brief label="Experience" value={profile?.experience}/><Brief label="Cardio" value={profile?.cardioPreference}/><Brief label="Training preferences" value={profile?.trainingPreferences}/><Brief label="Limitations" value={profile?.hasLimitations ? profile.limitationsText : "None reported"}/><Brief label="Personal priorities" value={profile?.personalPriorities}/><Brief label="Additional notes" value={profile?.additionalNotes}/></section><AdminProgrammeRequestWorkflow requestId={requestId} coachBrief={data.markdown}/></main></AppShell>; }
function Brief({ label, value }: { label: string; value: string | number | null | undefined }) { return <div className="rounded-2xl bg-background p-4"><p className="text-xs font-semibold uppercase tracking-wide text-primary">{label}</p><p className="mt-1 whitespace-pre-wrap text-sm">{value || "Not provided"}</p></div>; }
